# Generated by Django 3.1.5 on 2021-02-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backened', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transports',
            name='company_type_id',
            field=models.IntegerField(),
        ),
    ]
