# Generated by Django 3.1.5 on 2021-02-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backened', '0002_auto_20210211_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles_post',
            name='images',
            field=models.ImageField(blank=True, upload_to='media.article'),
        ),
    ]
