# Generated by Django 3.1.6 on 2021-02-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backened', '0003_articles_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_post',
            name='images',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
