# Generated by Django 3.1.5 on 2021-02-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backened', '0004_auto_20210212_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('Comments_name', models.CharField(max_length=150)),
                ('Comments_code', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
