# Generated by Django 3.1.5 on 2021-03-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backened', '0006_hotels_hotel_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_Map',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='city',
            name='city_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='city',
            name='city_imageLink',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='city',
            name='city_rating',
            field=models.FloatField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_Map',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='country',
            name='country_imageLink',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel_images',
            field=models.TextField(default='Add images Link'),
        ),
    ]
