# Generated by Django 3.1.5 on 2021-03-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backened', '0007_auto_20210317_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='hotels_location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hotels',
            name='hotels_roomprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articles_post',
            name='images',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel_details',
            field=models.TextField(default=''),
        ),
    ]
