# Generated by Django 3.1.6 on 2021-03-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backened', '0010_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_title_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title_name', models.CharField(max_length=255)),
            ],
        ),
    ]
