# Generated by Django 3.1.6 on 2021-03-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backened', '0011_done_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gallery_name', models.CharField(max_length=150)),
                ('Gallery_image', models.TextField(default='')),
            ],
        ),
    ]
